config/routes.rb
Rails.application.routes.draw do
  get 'home/about' => 'homes#about', as: 'about'
  devise_for :users
  root to: "homes#top"


  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  #get 'books/new'
  #get 'books/index'
  #get 'books/show'
  #get 'books/edit'

  resources :users, only: [:index, :show, :edit, :update]
  #get 'users/show'
  #get 'users/edit'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



  #get 'users/:id/edit' => 'users#edit', as: 'edit_user'
  patch 'users/:id' => 'users#update', as: 'update_user'





end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  has_one_attached :image
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true,
                   length: { maximum: 200 }





end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true, uniqueness: true,
                   length: { minimum: 2, maximum: 20 }

  validates :introduction,
                   length: { maximum: 50 }




  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')

    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
      user_path(current_user)
    end

    def after_sign_out_path_for(resource)
      root_path
    end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController



  before_action :correct_user, only: [:edit, :update]

  def new
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  # 投稿データの保存
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      @book_new = @book
      @user = current_user
      render :index
    end
  end

  def index
    #@books = Book.page(params[:page])
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    @user = current_user
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  # 投稿データのストロングパラメータ
  private

  def book_params
    params.require(:book).permit(:title, :body, :image)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.all
    @book = Book.new
    @books = Book.all

  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])

  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else

      render :edit
    end
    #redirect_to books_path(@book.id)
  end



  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def correct_user
    @user = User.find(params[:id])

    redirect_to(user_path(current_user.id)) unless @user == current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class = "col-md-3">
    <h2>User info</h2>
    <p><%= image_tag user.get_profile_image(100,100) %></p>
      <table class = "table">
        <tbody>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
            <tr>
              <th>introduction</th>
              <th><%= user.introduction %></th>
            </tr>
        </tbody>
      </table>
      <div class = "row">
        <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
        <% end %>
      </div>

      <h2 class = "mt-3">New book</h2>
      <%= form_with model: book, url: '/books', method: :post do |f| %>
      <form class="new_book" id="new_book" action="/books" accept-charset="UTF-8" method="post">
        <div class="field">
          <label for="book_title">Title</label>
     　    </br> <%= f.text_field :title %>
        </div>
        <div class="field">
          <label for="book_body">Opinion</label>
          </br><%= f.text_area :body %>
        </div>
        <div class="actions">
          <%= f.submit 'Create Book', class:"btn btn-sm btn-success btn-text-light" %>
        </div>
      <% end %>
  </div>

app/views/books/edit.html.erb
<main>
  <%= flash[:notice] %>
  <p id = "notice"></p>
  <div class = "container">
    <div class = "row">
      <div class = "col-sm-12 col-md8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>

        <% if @book.errors.any? %>
        <h2><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
        <% end %>

        <%= form_with model: @book do |f| %>
        <div class = "form-group">
          <label for="book_title">Title</label>
          </br><%= f.text_field :title %>
        </div>
        <div class = "field">
          <label for="book_body">Opinion</label>
          </br><%= f.text_area :body %>
        </div>
        <div class="actions">
          <%= f.submit 'Update Book', class:"btn btn-sm btn-success btn-text-light" %>
        </div>

        <div>
          <%= link_to "Show", book_path(@book.id) %>
           |
          <%= link_to "Back", "/books" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
  <% if @book.errors.any? %>
  <h2><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>

  <%= flash[:notice] %>
  <p id = "notice"></p>
  <div class = "container px-5 px-sm-0">
    <div class = "row">
      <%= render 'books/list', user: @user, book: @book %>

      <div class = "col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class = "table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan = "3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                <p><%= image_tag book.user.get_profile_image(100,100) %></p>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                <p><%= book.title %></p>
                <% end %>
              </td>
              <td>
                <p><%= book.body %></p>
              </td>

            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

</main>

app/views/books/new.html.erb
<main>
<% if @book.errors.any? %>
  <h2><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= flash[:notice] %>

<p id = "notice"></p>
  <div class = "container px-5 px-sm-0">
    <div class = "row">
      <%= render 'books/list', user: @user %>

      <div class = "col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class = "table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan = "3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                <p><%= image_tag book.user.get_profile_image(100,100) %></p>
                <% end %>
              </td>
              <td>
                <p><%= book.title %></p>
              </td>
              <td>
                <p><%= book.body %></p>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/show.html.erb
<main>
  <%= flash[:notice] %>
  <p id = "notice"></p>
  <div class = "container px-5 px-sm-0">
    <div class = "row">
      <%= render 'books/list', user: @user, book: @book_new %>

      <div class = "col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class = "table table-hover table-inverse">
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@book.user) do %>
                <p><%= image_tag @book.user.get_profile_image(100,100) %></p>
                <P><%= @user.name %></P>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(@book) do %>
                <p><%= @book.title %></p>
                <% end %>
              </td>
              <td>
                <p><%= @book.body %></p>
              </td>
              <% if @book.user == current_user %>
              <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-sm btn-success btn-text-light" %></td>
              <td><%= link_to "Destroy", book_path(@book.id), class:"btn btn-sm btn-danger btn-text-light", method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
              <% end %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/homes/about.html.erb
<main>
  <p id = "notice"></p>
  <div class = "container">
    <div class = "row">
      <h1 class = "px-3 mx-auto">
        Welcome to
        <i class="fas fa-book"></i>
        <strong>
          Bookers
        </strong>
        !
      </h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <%= flash[:notice] %>

  <script src="https://kit.fontawesome.com/ecf4eff661.js" crossorigin="anonymous"></script>
  <p id = "notice"></p>
  <div class = "container">
    <div class = "row">
      <div class = "mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>
          Welcome to
          <i class="fas fa-book"></i>
          <strong>Bookers</strong>
          !
        </h1>
        <p>
          In
          <i class="fas fa-book"></i>
          <strong>Bookers</strong>
          ,
        </p>
        <p>
          you can share and exchange your opinions , inpressions , and emotions
        </p>
        <p>
          about various books!
        </p>

        <div class = "btn-wrapper col-10 mx-auto">

          <td><%= link_to "Log in", new_user_session_url, class:"btn btn-info btn-sm btn-block mb-3 sign_in" %></td>
          <td><%= link_to "Sign up", new_user_registration_url, class:"btn btn-success btn-sm btn-block sign_up" %></td>


        </div>


      </div>
    </div>
  </div>

</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<script src="https://kit.fontawesome.com/ecf4eff661.js" crossorigin="anonymous"></script>
<html>
  <head>
    <title>Bookers2</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">


    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user), class: "nav-link text-light" do %>
              <i class="fas fa-home"></i>
              <tr>Home</tr>
              <% end %>
            </li>
            <li>
              <%= link_to user_registration_path, class: "nav-link text-light" do %>
              <i class="fas fa-users"></i>
              <tr>Users</tr>
              <% end %>
            </li>
            <li>
              <%= link_to books_path, class:"nav-link text-light" do %>
              <i class="fas fa-book-open"></i>
              <tr>Books</tr>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light" do %>
                <i class="fas fa-sign-out-alt"></i>
                Log out
              <% end %>
            </li>


            <% else %>
            <li>
              <%= link_to root_path, class: "nav-link text-light" do %>
              <i class="fas fa-home"></i>
              <tr>Home</tr>
              <% end %>
            </li>
            <li>
              <%= link_to about_path, class: "nav-link text-light" do %>
              <i class="fas fa-link"></i>
              <tr>About</tr>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
              <i class="fas fa-user-plus"></i>
              <tr>Sign up</tr>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path, class: "nav-link text-light" do %>
              <i class="fas fa-sign-in-alt"></i>
              <tr>Log in</tr>
              <% end %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>

    <footer>
      <div class = "container mt-5">
        <div class = "row">
          <div class = "mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<main>
  <p id = "notice"></p>
  <div class = "container">
    <div class = "row">
      <div class = "col-sm-12 col-md8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>User info</h1>
        <% if @user.errors.any? %>
          <h2><%= @user.errors.count %>errors prohibited this obj from being saved:</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>

        <%= form_with model: @user, url: user_path(@user.id), method: :patch do |f| %>
        <div class = "form-group">
          <label for="inputName">Name</label>
          </br><%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
        </div>
        <div class = "form-group">
          <label for="inputImage">Image</label>
          </br><%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
        </div>
        <div class = "form-group">
          <label for= "user_introduction">Introduction</label>
          </br><%= f.text_area :introduction, autofocus: true, id:"inputIntroduction" %>
        </div>
        <div class = "form-group">
          <%= f.submit "Update User", class:"btn btn-sm btn-secondary btn-text-light" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <p id = "notice"></p>
  <div class = "container px-5 px-sm-0">
    <div class = "row">
      <%= render 'books/list', user: current_user, book: @book %>

      <div class = "col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class = "table table-hover table-inverse">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
              <th colspan = "3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td>
                <%= image_tag user.get_profile_image(80,80) %>
              </td>
              <td>
                <p><%= user.name %></p>
              </td>
              <td>
                <%= link_to "Show", user_path(user.id) %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>

  <%= flash[:notice] %>
  <p id = "notice"></p>
  <div class = "container px-5 px-sm-0">
    <div class = "row">
      <div class = "col-md-3">
        <h2>User info</h2>
        <p><%= image_tag @user.get_profile_image(100,100) %></p>
        <table class = "table">
          <tbody>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class = "row">
          <%= link_to edit_user_path(@user), class: "btn btn-outline-secondary btn-block" do %>
          <i class="fas fa-user-cog"></i>
          <% end %>
        </div>

        <h2 class = "mt-3">New book</h2>
        <%= form_with model: @book, url: '/books', method: :post do |f| %>
        <form class="new_book" id="new_book" action="/books" accept-charset="UTF-8" method="post">
          <div class="field">
            <label for="book_title">Title</label>
     　      </br><%= f.text_field :title %>
          </div>
          <div class="field">
            <label for="book_body">Opinion</label>
             </br><%= f.text_area :body %>
          </div>
          <div class="actions">
            <%= f.submit "Create Book",  class:"btn btn-sm btn-success btn-text-light" %>
          </div>
        <% end %>

      </div>

      <div class = "col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class = "table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan = "3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                <p><%= image_tag book.user.get_profile_image(100,100) %></p>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book) do %>
                <p><%= book.title %></p>
                <% end %>
              </td>
              <td>
                <p><%= book.body %></p>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

</main>